# Generated by Django 4.0.4 on 2022-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.CharField(max_length=100),
        ),
    ]
