# Generated by Django 4.0.4 on 2022-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='WatchList',
        ),
    ]
