# Generated by Django 4.0.4 on 2022-05-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_streamplatform_rename_movie_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='App1.streamplatform'),
            preserve_default=False,
        ),
    ]
