# Generated by Django 4.0.4 on 2022-05-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_review_user_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_review',
            new_name='review_user',
        ),
    ]
