# Generated by Django 4.0.4 on 2022-06-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_watchlist_avg_rating_watchlist_num_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='num_rating',
        ),
    ]
