# Generated by Django 4.0.4 on 2022-06-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_remove_watchlist_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
